
import { University, Major } from './types';

export const UNIVERSITIES: University[] = [
  {
    id: 'uac',
    name: "Université d'Abomey-Calavi",
    acronym: 'UAC',
    location: 'Abomey-Calavi',
    type: 'Public',
    logo: 'https://images.unsplash.com/photo-1592280771190-3e2e4d571952?q=80&w=100',
    cover: 'https://images.unsplash.com/photo-1541339907198-e08756ebafe3?auto=format&fit=crop&q=80&w=1200',
    description: "Plus grande université du Bénin, pôle d'excellence multidisciplinaire.",
    isStandaloneSchool: false,
    stats: { students: '85,000+', majors: 150, founded: '1970', ranking: '1er National' },
    faculties: [
      { id: 'epac', name: "EPAC", description: 'Ingénierie', levels: ['Licence', 'Master'], type: 'Ecole' },
      { id: 'eneam', name: "ENEAM", description: 'Management', levels: ['Licence', 'Master'], type: 'Ecole' }
    ]
  },
  {
    id: 'up',
    name: "Université de Parakou",
    acronym: 'UP',
    location: 'Parakou',
    type: 'Public',
    logo: 'https://images.unsplash.com/photo-1562774053-701939374585?q=80&w=100',
    cover: 'https://images.unsplash.com/photo-1562774053-701939374585?auto=format&fit=crop&q=80&w=1200',
    description: "Deuxième pôle universitaire du pays.",
    isStandaloneSchool: false,
    stats: { students: '30,000+', majors: 85, founded: '2001', ranking: '2ème National' },
    faculties: [{ id: 'fsa-up', name: "FSA", description: 'Agronomie', levels: ['Licence', 'Master'], type: 'Faculté' }]
  },
  {
    id: 'hecm',
    name: "Hautes Études Commerciales et de Management",
    acronym: 'HECM',
    location: 'Cotonou',
    type: 'Privé',
    isStandaloneSchool: true,
    logo: 'https://images.unsplash.com/photo-1546410531-bb4caa6b424d?q=80&w=100',
    cover: 'https://images.unsplash.com/photo-1497366216548-37526070297c?auto=format&fit=crop&q=80&w=1200',
    description: "Leader de l'enseignement privé.",
    stats: { students: '15,000+', majors: 25, founded: '1999', ranking: '1er Privé' },
    faculties: []
  },
  {
    id: 'unstim',
    name: "Université des Sciences et Technologies",
    acronym: 'UNSTIM',
    location: 'Abomey',
    type: 'Public',
    isStandaloneSchool: false,
    logo: 'https://images.unsplash.com/photo-1581091226825-a6a2a5aee158?q=80&w=100',
    cover: 'https://images.unsplash.com/photo-1517048676732-d65bc937f952?q=80&w=1200',
    description: "Spécialisée en ingénierie et mathématiques.",
    stats: { students: '12,000+', majors: 45, founded: '2016', ranking: 'Top Innovation' },
    faculties: [{ id: 'insti', name: "INSTI", description: 'Technologie', levels: ['Licence'], type: 'Institut' }]
  },
  {
    id: 'ism-adonai',
    name: "Institut Supérieur Adonaï",
    acronym: 'ISM ADONAI',
    location: 'Cotonou',
    type: 'Privé',
    isStandaloneSchool: true,
    logo: 'https://images.unsplash.com/photo-1560179707-f14e90ef3623?q=80&w=100',
    cover: 'https://images.unsplash.com/photo-1431540015161-0bf868a2d407?q=80&w=1200',
    description: "Expertise en Audit et Comptabilité.",
    stats: { students: '5,000+', majors: 18, founded: '2005', ranking: 'Top Management' },
    faculties: []
  },
  {
    id: 'una',
    name: "Université Nationale d'Agriculture",
    acronym: 'UNA',
    location: 'Porto-Novo',
    type: 'Public',
    isStandaloneSchool: false,
    logo: 'https://images.unsplash.com/photo-1592982537447-7440770cbfc9?q=80&w=100',
    cover: 'https://images.unsplash.com/photo-1500382017468-9049fed747ef?q=80&w=1200',
    description: "Dédiée à la souveraineté alimentaire.",
    stats: { students: '8,000+', majors: 30, founded: '2016', ranking: 'Leader Agrotech' },
    faculties: [{ id: 'ensta', name: "ENSTA", description: 'Agronomie', levels: ['Licence'], type: 'Ecole' }]
  },
  {
    id: 'esgis',
    name: "ESGIS Bénin",
    acronym: 'ESGIS',
    location: 'Cotonou',
    type: 'Privé',
    isStandaloneSchool: true,
    logo: 'https://images.unsplash.com/photo-1523240795612-9a054b0db644?q=80&w=100',
    cover: 'https://images.unsplash.com/photo-1524178232363-1fb2b075b655?q=80&w=1200',
    description: "Spécialiste du tertiaire et de l'informatique.",
    stats: { students: '3,500', majors: 12, founded: '2008', ranking: 'Top Privé' },
    faculties: []
  },
  {
    id: 'upn',
    name: "Université de Porto-Novo",
    acronym: 'UPN',
    location: 'Porto-Novo',
    type: 'Public',
    isStandaloneSchool: false,
    logo: 'https://images.unsplash.com/photo-1519452575417-564c1401ecc0?q=80&w=100',
    cover: 'https://images.unsplash.com/photo-1519452575417-564c1401ecc0?q=80&w=1200',
    description: "Pôle de sciences sociales et humaines.",
    stats: { students: '20,000', majors: 40, founded: '2010', ranking: '4ème National' },
    faculties: [{ id: 'fashs', name: "FASHS", description: 'Lettres', levels: ['Licence'], type: 'Faculté' }]
  },
  {
    id: 'cerco',
    name: "Groupe Cerco",
    acronym: 'CERCO',
    location: 'Cotonou',
    type: 'Privé',
    isStandaloneSchool: true,
    logo: 'https://images.unsplash.com/photo-1551033406-611cf9a28f67?q=80&w=100',
    cover: 'https://images.unsplash.com/photo-1551033406-611cf9a28f67?q=80&w=1200',
    description: "Innovation technologique et management.",
    stats: { students: '4,000', majors: 15, founded: '1998', ranking: 'Innovateur' },
    faculties: []
  },
  {
    id: 'uak',
    name: "Université d'Agriculture de Kétou",
    acronym: 'UAK',
    location: 'Kétou',
    type: 'Public',
    isStandaloneSchool: false,
    logo: 'https://images.unsplash.com/photo-1523348837708-15d4a09cfac2?q=80&w=100',
    cover: 'https://images.unsplash.com/photo-1523348837708-15d4a09cfac2?q=80&w=1200',
    description: "Recherche agronomique avancée.",
    stats: { students: '5,000', majors: 20, founded: '2012', ranking: 'Spécialisé' },
    faculties: [{ id: 'enat', name: "ENAT", description: 'Agro-technologie', levels: ['Licence'], type: 'Ecole' }]
  },
  {
    id: 'pigier',
    name: "Pigier Bénin",
    acronym: 'PIGIER',
    location: 'Cotonou',
    type: 'Privé',
    isStandaloneSchool: true,
    logo: 'https://images.unsplash.com/photo-1541339907198-e08756ebafe3?q=80&w=100',
    cover: 'https://images.unsplash.com/photo-1541339907198-e08756ebafe3?q=80&w=1200',
    description: "Formation d'excellence aux métiers de l'entreprise.",
    stats: { students: '3,000', majors: 10, founded: '1995', ranking: 'Référence' },
    faculties: []
  },
  {
    id: 'eneam-standalone',
    name: "Ecole Nationale d'Economie Appliquée et de Management",
    acronym: 'ENEAM',
    location: 'Cotonou',
    type: 'Public',
    isStandaloneSchool: true,
    logo: 'https://images.unsplash.com/photo-1551288049-bbda38656ad1?q=80&w=100',
    cover: 'https://images.unsplash.com/photo-1551288049-bbda38656ad1?q=80&w=1200',
    description: "Pôle d'excellence en économie et gestion.",
    stats: { students: '6,000', majors: 12, founded: '1980', ranking: 'Prestigieuse' },
    faculties: []
  }
];

export const MAJORS: Major[] = [
  {
    id: 'uac-gl',
    name: "Génie Logiciel",
    universityId: 'uac',
    universityName: "UAC (EPAC)",
    facultyName: 'EPAC',
    domain: 'Informatique',
    level: 'Licence',
    duration: '3 Ans',
    fees: '450.000 FCFA',
    location: 'Abomey-Calavi',
    image: 'https://images.unsplash.com/photo-1517694712202-14dd9538aa97?q=80&w=400',
    careerProspects: [{ title: "Développeur", icon: "code" }, { title: "Architecte IT", icon: "architecture" }],
    requiredDiplomas: [{ name: "BAC C / D / E", icon: "school" }]
  },
  {
    id: 'uac-stats',
    name: "Statistique",
    universityId: 'uac',
    universityName: "UAC (ENEAM)",
    facultyName: 'ENEAM',
    domain: 'Économie',
    level: 'Licence',
    duration: '3 Ans',
    fees: '400.000 FCFA',
    location: 'Cotonou',
    image: 'https://images.unsplash.com/photo-1551288049-bbda38656ad1?q=80&w=400',
    careerProspects: [{ title: "Statisticien", icon: "analytics" }],
    requiredDiplomas: [{ name: "BAC C / D", icon: "calculate" }]
  },
  {
    id: 'up-med',
    name: "Médecine",
    universityId: 'up',
    universityName: "Université de Parakou",
    facultyName: 'Médecine',
    domain: 'Santé',
    level: 'Doctorat',
    duration: '8 Ans',
    fees: 'Gratuit (Public)',
    location: 'Parakou',
    image: 'https://images.unsplash.com/photo-1576091160550-2173dba999ef?q=80&w=400',
    careerProspects: [{ title: "Médecin", icon: "medical_services" }],
    requiredDiplomas: [{ name: "BAC C / D", icon: "science" }]
  },
  {
    id: 'hecm-mark',
    name: "Marketing Digital",
    universityId: 'hecm',
    universityName: "HECM",
    facultyName: "Gestion",
    domain: "Management",
    level: 'Licence',
    duration: '3 Ans',
    fees: '385.000 FCFA',
    location: 'Cotonou',
    image: 'https://images.unsplash.com/photo-1557804506-669a67965ba0?q=80&w=400',
    careerProspects: [{ title: "Social Media Manager", icon: "campaign" }],
    requiredDiplomas: [{ name: "BAC Toutes séries", icon: "school" }]
  },
  {
    id: 'unstim-nrj',
    name: "Énergies Renouvelables",
    universityId: 'unstim',
    universityName: "UNSTIM",
    facultyName: 'INSTI',
    domain: 'Énergie',
    level: 'Licence',
    duration: '3 Ans',
    fees: '450.000 FCFA',
    location: 'Abomey',
    image: 'https://images.unsplash.com/photo-1508514177221-188b1cf16e9d?q=80&w=400',
    careerProspects: [{ title: "Expert Photovoltaïque", icon: "wb_sunny" }],
    requiredDiplomas: [{ name: "BAC C / D / E / F", icon: "bolt" }]
  },
  {
    id: 'ism-audit',
    name: "Audit et Contrôle",
    universityId: 'ism-adonai',
    universityName: "ISM Adonaï",
    facultyName: "Expertise",
    domain: "Finances",
    level: 'Master',
    duration: '2 Ans',
    fees: '650.000 FCFA',
    location: 'Cotonou',
    image: 'https://images.unsplash.com/photo-1450101499163-c8848c66ca85?q=80&w=400',
    careerProspects: [{ title: "Auditeur Externe", icon: "search" }],
    requiredDiplomas: [{ name: "Licence en Gestion", icon: "history_edu" }]
  },
  {
    id: 'esgis-cyber',
    name: "Cybersécurité",
    universityId: 'esgis',
    universityName: "ESGIS",
    facultyName: "Technologie",
    domain: "Informatique",
    level: 'Licence',
    duration: '3 Ans',
    fees: '500.000 FCFA',
    location: 'Cotonou',
    image: 'https://images.unsplash.com/photo-1550751827-4bd374c3f58b?q=80&w=400',
    careerProspects: [{ title: "Analyste Sécurité", icon: "lock" }],
    requiredDiplomas: [{ name: "BAC C / D / E", icon: "terminal" }]
  },
  {
    id: 'una-agro',
    name: "Agro-Industrie",
    universityId: 'una',
    universityName: "UNA",
    facultyName: 'ENSTA',
    domain: 'Agriculture',
    level: 'Licence',
    duration: '3 Ans',
    fees: '185.000 FCFA',
    location: 'Sakété',
    image: 'https://images.unsplash.com/photo-1516467508483-a7212febe31a?q=80&w=400',
    careerProspects: [{ title: "Ingénieur Agronome", icon: "pets" }],
    requiredDiplomas: [{ name: "BAC D", icon: "grass" }]
  },
  {
    id: 'upn-droit',
    name: "Droit des Affaires",
    universityId: 'upn',
    universityName: "UPN",
    facultyName: 'FADESP',
    domain: 'Droit',
    level: 'Master',
    duration: '2 Ans',
    fees: '250.000 FCFA',
    location: 'Porto-Novo',
    image: 'https://images.unsplash.com/photo-1589829545856-d10d557cf95f?q=80&w=400',
    careerProspects: [{ title: "Juriste d'entreprise", icon: "gavel" }],
    requiredDiplomas: [{ name: "Licence en Droit", icon: "menu_book" }]
  },
  {
    id: 'cerco-web',
    name: "Web & Mobile Design",
    universityId: 'cerco',
    universityName: "CERCO",
    facultyName: "Design",
    domain: "Art Digital",
    level: 'Licence',
    duration: '3 Ans',
    fees: '480.000 FCFA',
    location: 'Cotonou',
    image: 'https://images.unsplash.com/photo-1502945015378-0e284ca1a5be?q=80&w=400',
    careerProspects: [{ title: "UI/UX Designer", icon: "palette" }],
    requiredDiplomas: [{ name: "BAC Toutes séries", icon: "brush" }]
  },
  {
    id: 'uak-prod',
    name: "Production Végétale",
    universityId: 'uak',
    universityName: "UAK",
    facultyName: 'ENAT',
    domain: 'Agronomie',
    level: 'Licence',
    duration: '3 Ans',
    fees: '185.000 FCFA',
    location: 'Kétou',
    image: 'https://images.unsplash.com/photo-1495107336281-19d4f7a4ca0c?q=80&w=400',
    careerProspects: [{ title: "Chef d'exploitation", icon: "agriculture" }],
    requiredDiplomas: [{ name: "BAC D", icon: "eco" }]
  },
  {
    id: 'pigier-rh',
    name: "Ressources Humaines",
    universityId: 'pigier',
    universityName: "PIGIER",
    facultyName: "Management",
    domain: "Gestion",
    level: 'Licence',
    duration: '3 Ans',
    fees: '550.000 FCFA',
    location: 'Cotonou',
    image: 'https://images.unsplash.com/photo-1521737711867-e3b97375f902?q=80&w=400',
    careerProspects: [{ title: "Responsable RH", icon: "badge" }],
    requiredDiplomas: [{ name: "BAC G2 / A / B / D", icon: "people" }]
  },
  {
    id: 'eneam-compta',
    name: "Comptabilité Gestion",
    universityId: 'eneam-standalone',
    universityName: "ENEAM",
    facultyName: "Finance",
    domain: "Commerce",
    level: 'Licence',
    duration: '3 Ans',
    fees: '150.000 FCFA (Public)',
    location: 'Cotonou',
    image: 'https://images.unsplash.com/photo-1554224155-6726b3ff858f?q=80&w=400',
    careerProspects: [{ title: "Comptable", icon: "account_balance_wallet" }],
    requiredDiplomas: [{ name: "BAC G2", icon: "payments" }]
  },
  {
    id: 'uac-bio',
    name: "Biologie Humaine",
    universityId: 'uac',
    universityName: "UAC (FAST)",
    facultyName: 'FAST',
    domain: 'Sciences',
    level: 'Licence',
    duration: '3 Ans',
    fees: 'Gratuit',
    location: 'Abomey-Calavi',
    image: 'https://images.unsplash.com/photo-1532187863486-abf51ad9f69d?q=80&w=400',
    careerProspects: [{ title: "Biologiste", icon: "biotechnology" }],
    requiredDiplomas: [{ name: "BAC C / D", icon: "science" }]
  }
];
